"""
ITL Control Plane API Client
Supports communication with resource providers directly or via API Gateway
"""
import requests
import json
from typing import Optional, Dict, List, Any
from pathlib import Path
import os


class ControlPlaneClient:
    """
    Client for interacting with ITL Control Plane API.
    Supports both direct communication and gateway-based access.
    """
    
    def __init__(self, base_url: str = None, access_token: str = None, use_gateway: bool = False):
        """
        Initialize ControlPlaneClient.
        
        Args:
            base_url: API base URL (direct provider or gateway URL)
                     Default: http://localhost:8000 (direct) or https://api.itlusions.com (gateway)
            access_token: Bearer token for authentication
            use_gateway: If True, use gateway URL; if False, use direct provider URL
        """
        self.use_gateway = use_gateway
        
        if base_url:
            self.base_url = base_url.rstrip('/')
        else:
            if use_gateway:
                self.base_url = os.getenv('CONTROLPLANE_GATEWAY_URL', 'https://api.itlusions.com')
            else:
                self.base_url = os.getenv('CONTROLPLANE_URL', 'http://localhost:8000')
        
        self.access_token = access_token
        self.headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }
        
        if self.access_token:
            self.headers['Authorization'] = f'Bearer {self.access_token}'
    
    def set_token(self, access_token: str):
        """Update the authorization token"""
        self.access_token = access_token
        if access_token:
            self.headers['Authorization'] = f'Bearer {self.access_token}'
    
    # ==================== HEALTH & INFO ====================
    
    def health(self) -> bool:
        """Check API health"""
        try:
            response = requests.get(f"{self.base_url}/health", headers=self.headers, timeout=10)
            return response.status_code == 200
        except Exception:
            return False
    
    def get_openapi_spec(self) -> Optional[Dict]:
        """Get OpenAPI specification"""
        try:
            response = requests.get(f"{self.base_url}/openapi.json", headers=self.headers, timeout=10)
            if response.status_code == 200:
                return response.json()
            return None
        except Exception as e:
            print(f"Error getting OpenAPI spec: {e}")
            return None
    
    # ==================== SUBSCRIPTIONS ====================
    
    def create_subscription(self, 
                          resource_name: str,
                          resource_group: str,
                          location: str,
                          display_name: str,
                          state: str = 'Enabled',
                          subscription_id: str = None,
                          tags: Dict[str, str] = None,
                          properties: Dict[str, Any] = None) -> Optional[Dict]:
        """
        Create a subscription.
        
        The subscription_id is auto-generated by the server if not provided.
        
        Args:
            resource_name: Subscription resource name
            resource_group: Resource group name
            location: Location (e.g., 'westeurope')
            display_name: User-friendly display name
            state: Subscription state (default: 'Enabled')
            subscription_id: Optional subscription ID (will be auto-generated if not provided)
            tags: Optional tags dictionary
            properties: Optional properties dictionary
            
        Returns:
            Created subscription object or None on failure
        """
        try:
            payload = {
                'resource_name': resource_name,
                'resource_group': resource_group,
                'resource_type': 'subscriptions',
                'location': location,
                'display_name': display_name,
                'state': state
            }
            
            if subscription_id:
                payload['subscription_id'] = subscription_id
            if tags:
                payload['tags'] = tags
            if properties:
                payload['properties'] = properties
            
            response = requests.post(
                f"{self.base_url}/subscriptions",
                headers=self.headers,
                json=payload,
                timeout=30
            )
            
            if response.status_code in [200, 201]:
                return response.json()
            else:
                print(f"Error creating subscription: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def list_subscriptions(self) -> Optional[Dict]:
        """List all subscriptions"""
        try:
            response = requests.get(
                f"{self.base_url}/subscriptions",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def get_subscription(self, subscription_name: str) -> Optional[Dict]:
        """Get specific subscription"""
        try:
            response = requests.get(
                f"{self.base_url}/subscriptions/{subscription_name}",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def delete_subscription(self, subscription_name: str) -> bool:
        """Delete subscription"""
        try:
            response = requests.delete(
                f"{self.base_url}/subscriptions/{subscription_name}",
                headers=self.headers,
                timeout=30
            )
            return response.status_code in [200, 204]
                
        except Exception as e:
            print(f"Error: {e}")
            return False
    
    # ==================== LOCATIONS ====================
    
    def list_locations(self) -> Optional[Dict]:
        """List available locations"""
        try:
            response = requests.get(
                f"{self.base_url}/locations",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                data = response.json()
                # Convert resources array to locations for consistency
                if 'resources' in data and not 'locations' in data:
                    data['locations'] = [
                        {
                            'name': loc.get('name'),
                            'shortname': loc.get('properties', {}).get('shortname'),
                            'country': loc.get('properties', {}).get('region')
                        }
                        for loc in data['resources']
                    ]
                return data
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def list_extended_locations(self) -> Optional[Dict]:
        """List extended locations (custom locations)"""
        try:
            response = requests.get(
                f"{self.base_url}/extendedlocations",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    # ==================== RESOURCE GROUPS ====================
    
    def create_resource_group(self,
                            subscription_id: str,
                            resource_name: str,
                            location: str,
                            display_name: str = None,
                            tags: Dict[str, str] = None) -> Optional[Dict]:
        """
        Create a resource group in a subscription.
        Resource group names are unique within a subscription.
        
        Args:
            subscription_id: Subscription ID
            resource_name: Resource group name (unique within subscription)
            location: Location (e.g., 'eastus')
            display_name: Optional display name
            tags: Optional tags dictionary
            
        Returns:
            Created resource group object or None on failure
        """
        try:
            payload = {
                'subscription_id': subscription_id,
                'resource_group': resource_name,
                'resource_name': resource_name,
                'resource_type': 'resourcegroups',
                'location': location,
                'display_name': display_name or resource_name
            }
            
            if tags:
                payload['tags'] = tags
            
            response = requests.post(
                f"{self.base_url}/subscriptions/{subscription_id}/resourcegroups",
                headers=self.headers,
                json=payload,
                timeout=30
            )
            
            if response.status_code in [200, 201]:
                return response.json()
            elif response.status_code == 409:
                print(f"Resource group '{resource_name}' already exists in subscription {subscription_id}")
                return None
            else:
                print(f"Error creating resource group: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def get_resource_group(self, subscription_id: str, resource_name: str) -> Optional[Dict]:
        """Get a resource group from a subscription"""
        try:
            response = requests.get(
                f"{self.base_url}/subscriptions/{subscription_id}/resourcegroups/{resource_name}",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            elif response.status_code == 404:
                print(f"Resource group '{resource_name}' not found in subscription {subscription_id}")
                return None
            else:
                print(f"Error getting resource group: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def list_resource_groups(self, subscription_id: str) -> Optional[Dict]:
        """
        List resource groups in a subscription.
        
        Args:
            subscription_id: Subscription ID
            
        Returns:
            Dictionary with 'resources' list and 'count'
        """
        try:
            response = requests.get(
                f"{self.base_url}/subscriptions/{subscription_id}/resourcegroups",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            else:
                print(f"Error listing resource groups: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def delete_resource_group(self, subscription_id: str, resource_name: str) -> Optional[Dict]:
        """
        Delete a resource group from a subscription.
        
        Args:
            subscription_id: Subscription ID
            resource_name: Resource group name
            
        Returns:
            Deletion response or None on failure
        """
        try:
            response = requests.delete(
                f"{self.base_url}/subscriptions/{subscription_id}/resourcegroups/{resource_name}",
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            elif response.status_code == 404:
                print(f"Resource group '{resource_name}' not found in subscription {subscription_id}")
                return None
            else:
                print(f"Error deleting resource group: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    # ==================== DEPLOYMENTS ====================
    
    def list_deployments(self, subscription_id: str = None, resource_group: str = None) -> Optional[Dict]:
        """List deployments"""
        try:
            url = f"{self.base_url}/deployments"
            params = []
            if subscription_id:
                params.append(f"subscription_id={subscription_id}")
            if resource_group:
                params.append(f"resource_group={resource_group}")
            
            if params:
                url += "?" + "&".join(params)
            
            response = requests.get(
                url,
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def create_deployment(self,
                         subscription_id: str,
                         resource_group: str,
                         resource_name: str,
                         deployment_body: Dict[str, Any],
                         location: str = 'global') -> Optional[Dict]:
        """Create a deployment"""
        try:
            payload = {
                'subscription_id': subscription_id,
                'resource_group': resource_group,
                'resource_name': resource_name,
                'resource_type': 'deployments',
                'location': location,
                'body': deployment_body
            }
            
            response = requests.post(
                f"{self.base_url}/deployments",
                headers=self.headers,
                json=payload,
                timeout=30
            )
            
            if response.status_code in [200, 201]:
                return response.json()
            else:
                print(f"Error creating deployment: {response.status_code} - {response.text}")
                return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def get_deployment(self, deployment_name: str, subscription_id: str = None, resource_group: str = None) -> Optional[Dict]:
        """Get specific deployment"""
        try:
            url = f"{self.base_url}/deployments/{deployment_name}"
            params = []
            if subscription_id:
                params.append(f"subscription_id={subscription_id}")
            if resource_group:
                params.append(f"resource_group={resource_group}")
            
            if params:
                url += "?" + "&".join(params)
            
            response = requests.get(
                url,
                headers=self.headers,
                timeout=30
            )
            
            if response.status_code == 200:
                return response.json()
            return None
                
        except Exception as e:
            print(f"Error: {e}")
            return None
    
    def delete_deployment(self, deployment_name: str, subscription_id: str = None, resource_group: str = None) -> bool:
        """Delete deployment"""
        try:
            url = f"{self.base_url}/deployments/{deployment_name}"
            params = []
            if subscription_id:
                params.append(f"subscription_id={subscription_id}")
            if resource_group:
                params.append(f"resource_group={resource_group}")
            
            if params:
                url += "?" + "&".join(params)
            
            response = requests.delete(
                url,
                headers=self.headers,
                timeout=30
            )
            return response.status_code in [200, 204]
                
        except Exception as e:
            print(f"Error: {e}")
            return False
